### ISSUE TITLE
CurseForge Post?

### ISSUE THREAD

**Issue by NikorinMP** [Voidlighter/MinimalArmor#1]
Hello, I'm not used to GitHub, so I'm posting this here.

Have you considered posting these resourcepacks on CurseForge? It took me a while to find this specific texture pack I saw a Youtuber using (Grian).
I was wondering if you could add them on CurseForge or if you would give me permission to upload them on there. I would not take any credit whatsoever and I would link the resourcepacks to this Github page and to the planetminecraft post. (Which is were I originally found the textures).
My sole intention is to facilitate these armors to the people looking for it.
I hope you are doing well and I'll be waiting for your response.

**Comment by Voidlighter** [comment]
Wow I never saw that someone took the time to post an issue here, sorry! I am making a CurseForge and Modrinth page right now, with the big update that I just brought to the pack. Hope you enjoy!
